DELETE http://localhost:3003/api/blogs/636cf540a1d0dbc9a5d69d16
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inh5bCIsImlkIjoiNjM2Y2Y0ZDJhMWQwZGJjOWE1ZDY5ZDBmIiwiaWF0IjoxNjY4MTU2OTY0LCJleHAiOjE2NjgxNjA1NjR9.wiY7pIn1MNl5sqFGc0vPG8AS1R_-QqG92S758Jwee_A

